### 출근 시간 등록
POST http://localhost:8080/commutes
Content-Type: application/json

{
  "memberId": 2024001003,
  "workingDate": "2024-04-30",
  "startWork": "08:45",
  "workingStatus": "근무중",
  "totalWorkingHours": 0
}

### 퇴근 시간 등록
PUT http://localhost:8080/commutes/17
Content-Type: application/json

{
  "endWork": "17:45",
  "workingStatus": "퇴근",
  "totalWorkingHours": "480"
}