### 출근 시간 등록
POST http://localhost:8080/commutes
Content-Type: application/json

{
  "memberId": 2024001001,
  "workingDate": "2024-05-01",
  "startWork": "08:45",
  "workingStatus": "근무중",
  "totalWorkingHours": 0
}

### 퇴근 시간 등록
PUT http://localhost:8080/commutes/23
Content-Type: application/json

{
  "endWork": "17:45",
  "workingStatus": "퇴근",
  "totalWorkingHours": "480"
}

### 부서별 출퇴근 시간 조회
GET http://localhost:8080/commutes?target=depart&targetValue=1&date=2024-05-01

### 멤버별 출퇴근 시간 조회
GET http://localhost:8080/commutes?target=member&targetValue=2024001001&date=2024-05-01